project_id = "pbsqmaomyaiexgajfrsa"

[functions.generate-content]
verify_jwt = false

[functions.generate-download]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.scrape-trends]
verify_jwt = false
